name: Daily CheckIn

on:
  schedule:
    - cron: '0 15 * * *'  # 每天北京时间 23:00 (UTC 15:00)
  workflow_dispatch:

jobs:
  check-in:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Show public IP
      run: |
        echo "Public IP:"
        curl -s ifconfig.me
        echo
        echo "IP info:"
        curl -s ipinfo.io
        
    - name: Run Daily CheckIn
      run: python RunCheckIn.py
      env:
        CONFIG_CHECKIN: ${{ secrets.CONFIG_CHECKIN }}
